// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9kL56DsBAAeGSa52kwYvaujC1peEFDaM',
    appId: '1:866150652476:web:5ce9c0aee27bd1b4114139',
    messagingSenderId: '866150652476',
    projectId: 'fire-set-a7ea2',
    authDomain: 'fire-set-a7ea2.firebaseapp.com',
    storageBucket: 'fire-set-a7ea2.firebasestorage.app',
    measurementId: 'G-SZ6LWZLRGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP-s1b9fzTT5nLkYYGOu4Y2L6aiAe1vis',
    appId: '1:866150652476:android:e758af0513b241fb114139',
    messagingSenderId: '866150652476',
    projectId: 'fire-set-a7ea2',
    storageBucket: 'fire-set-a7ea2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn2lEgbWhotu5nIWrWGFSVsiLCr4SysNg',
    appId: '1:866150652476:ios:4c04ee8a7a82e081114139',
    messagingSenderId: '866150652476',
    projectId: 'fire-set-a7ea2',
    storageBucket: 'fire-set-a7ea2.firebasestorage.app',
    iosBundleId: 'com.example.listtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn2lEgbWhotu5nIWrWGFSVsiLCr4SysNg',
    appId: '1:866150652476:ios:4c04ee8a7a82e081114139',
    messagingSenderId: '866150652476',
    projectId: 'fire-set-a7ea2',
    storageBucket: 'fire-set-a7ea2.firebasestorage.app',
    iosBundleId: 'com.example.listtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9kL56DsBAAeGSa52kwYvaujC1peEFDaM',
    appId: '1:866150652476:web:b3fe737e58f40e14114139',
    messagingSenderId: '866150652476',
    projectId: 'fire-set-a7ea2',
    authDomain: 'fire-set-a7ea2.firebaseapp.com',
    storageBucket: 'fire-set-a7ea2.firebasestorage.app',
    measurementId: 'G-ZHPD0J7N9D',
  );
}
